# sudo: required
language: ruby

rvm:
  - 2.3.0

#Neo4j workaround
jdk:
  - oraclejdk8

before_install:
# install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-3.0.1-unix.tar.gz
  - tar -xzf neo4j-community-3.0.1-unix.tar.gz
  - sed -i.bak s/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g neo4j-community-3.0.1/conf/neo4j.conf
  - neo4j-community-3.0.1/bin/neo4j start
  - tail -n 500 neo4j-community-3.0.1/logs/neo4j.log
  - sleep 5
  - tail -n 20 neo4j-community-3.0.1/logs/neo4j.log
  - sleep 5
  - tail -n 20 neo4j-community-3.0.1/logs/neo4j.log
  - sleep 5
  - tail -n 20 neo4j-community-3.0.1/logs/neo4j.log
  - sleep 5
  - tail -n 20 neo4j-community-3.0.1/logs/neo4j.log


services:
  - mongodb
  - riak
  - cassandra

script:
- bundle exec ruby test/all_suite.rb