# sudo: required
language: ruby

rvm:
  - 2.3.0

#Neo4j workaround
jdk:
  - oraclejdk8

#before_install:
# install Neo4j locally:
#  - wget dist.neo4j.org/neo4j-community-2.3.4-unix.tar.gz
#  - tar -xzf neo4j-community-2.3.4-unix.tar.gz
#  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.3.4/conf/neo4j-server.properties
#  - neo4j-community-2.3.4/bin/neo4j start

services:
  - mongodb
  - riak
  - cassandra
  - neo4j

script:
- bundle exec ruby test/all_suite.rb