mongo:
  image: mongo
  ports:
    - "27017:27017"


cassandra:
  image: cassandra

neo4j:
  image: neo4j
  ports:
    - "7474:7474"
    - "7473:7473"

riak:
  build: ./riak
  ports:
    - "8087:8087"
    - "8098:8098"
